northbound = {"Walthamstow Central" : "",
              "Blackhorse Road" : "Walthamstow Central", 
              "Tottenham Hale" : "Blackhorse Road",
              "Seven Sisters" :  "Tottenham Hale",
              "Finsbury Park" : "Seven Sisters",
              "Highbury & Islington" : "Finsbury Park",
              "King's Cross St. Pancras" : "Highbury & Islington",
              "Euston" : "King's Cross St. Pancras",
              "Warren Street" : "Euston",
              "Oxford Circus" : "Warren Street",
              "Green Park" : "Oxford Circus",
              "Victoria" : "Green Park",
              "Pimlico" : "Victoria",
              "Vauxhall" : "Pimlico",
              "Stockwell" : "Vauxhall",
              "Brixton" : "Stockwell"}

southbound = {"Brixton" : "",
              "Stockwell" : "Brixton",
              "Vauxhall" : "Stockwell",
              "Pimlico" : "Vauxhall",
              "Victoria" : "Pimlico",
              "Green Park" : "Victoria",
              "Oxford Circus" : "Green Park",
              "Warren Street" : "Oxford Circus",
              "Euston" : "Warren Street",
              "King's Cross St. Pancras" : "Euston",
              "Highbury & Islington" : "King's Cross St. Pancras",
              "Finsbury Park" : "Highbury & Islington",
              "Seven Sisters" : "Finsbury Park",
              "Tottenham Hale" : "Seven Sisters",
              "Blackhorse Road" : "Tottenham Hale",
              "Walthamstow Central" :  "Blackhorse Road"}